"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-23

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Every expense's splits must sum exactly to its amount. Checked at COMMIT (deferred) so an
# expense and its splits can be written, or rewritten, in any order inside one transaction.
SPLIT_SUM_CHECK = """
CREATE FUNCTION check_expense_split_sum() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    eid uuid;
    total bigint;
    allocated bigint;
BEGIN
    IF TG_TABLE_NAME = 'expenses' THEN
        eid := NEW.id;
    ELSIF TG_OP = 'DELETE' THEN
        eid := OLD.expense_id;
    ELSE
        eid := NEW.expense_id;
    END IF;

    SELECT amount_minor INTO total FROM expenses WHERE id = eid;
    IF NOT FOUND THEN
        RETURN NULL;  -- the expense itself was hard-deleted; its splits cascade away
    END IF;
    SELECT COALESCE(SUM(share_minor), 0) INTO allocated FROM expense_splits WHERE expense_id = eid;
    IF allocated <> total THEN
        RAISE EXCEPTION 'expense % splits sum to % but amount is %', eid, allocated, total
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END
$$;

CREATE CONSTRAINT TRIGGER expense_splits_sum_matches
    AFTER INSERT OR UPDATE OR DELETE ON expense_splits
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION check_expense_split_sum();

CREATE CONSTRAINT TRIGGER expenses_split_sum_matches
    AFTER INSERT OR UPDATE OF amount_minor ON expenses
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION check_expense_split_sum();
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), server_default="INR", nullable=False),
        sa.Column("role", sa.Text(), server_default="user", nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('user', 'admin')", name=op.f("ck_users_role")),
        sa.CheckConstraint(
            "password_hash IS NULL OR email IS NOT NULL", name=op.f("ck_users_login_needs_email")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "uq_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "admin_sessions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("admin_id", sa.UUID(), nullable=False),
        sa.Column("target_user_id", sa.UUID(), nullable=False),
        sa.Column("mode", sa.Text(), server_default="read_only", nullable=False),
        sa.Column(
            "started_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint("mode IN ('read_only', 'edit')", name=op.f("ck_admin_sessions_mode")),
        sa.ForeignKeyConstraint(
            ["admin_id"], ["users.id"], name=op.f("fk_admin_sessions_admin_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"], ["users.id"], name=op.f("fk_admin_sessions_target_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_sessions")),
    )
    op.create_table(
        "analytics_configuration",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("period", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column(
            "params_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "scope IN ('personal', 'group')", name=op.f("ck_analytics_configuration_scope")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_analytics_configuration_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analytics_configuration")),
    )
    op.create_index(
        "ix_analytics_configuration_scope_owner",
        "analytics_configuration",
        ["scope", "owner_id", "position"],
        unique=False,
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("acting_as_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "diff_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["acting_as_id"], ["users.id"], name=op.f("fk_audit_logs_acting_as_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_logs_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_logs_at", "audit_logs", [sa.literal_column("at DESC")], unique=False)
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("icon", sa.Text(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("sort", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "scope IN ('group', 'personal', 'all')", name=op.f("ck_categories_scope")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_categories_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    op.create_index(
        "uq_categories_owner_key",
        "categories",
        ["owner_id", "key"],
        unique=True,
        postgresql_where=sa.text("owner_id IS NOT NULL"),
    )
    op.create_index(
        "uq_categories_system_key",
        "categories",
        ["key"],
        unique=True,
        postgresql_where=sa.text("owner_id IS NULL"),
    )
    op.create_table(
        "groups",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), server_default="INR", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_groups_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_groups")),
    )
    op.create_table(
        "activity_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("acting_admin_id", sa.UUID(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("entity", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column(
            "at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["acting_admin_id"], ["users.id"], name=op.f("fk_activity_events_acting_admin_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_activity_events_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_activity_events_group_id_groups")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_events")),
    )
    op.create_index(
        "ix_activity_events_group_at",
        "activity_events",
        ["group_id", sa.literal_column("at DESC")],
        unique=False,
    )
    op.create_table(
        "group_members",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Text(), server_default="member", nullable=False),
        sa.Column(
            "joined_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("left_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("placeholder_name", sa.Text(), nullable=True),
        sa.CheckConstraint("role IN ('owner', 'member')", name=op.f("ck_group_members_role")),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_group_members_group_id_groups")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_group_members_user_id_users")
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id", name=op.f("pk_group_members")),
    )
    op.create_index(op.f("ix_group_members_user_id"), "group_members", ["user_id"], unique=False)
    op.create_table(
        "import_batches",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source", sa.Text(), server_default="tricount", nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=True),
        sa.Column(
            "stats_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("undone_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_import_batches_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_import_batches_group_id_groups")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
    )
    op.create_table(
        "personal_transactions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("acting_admin_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "type IN ('income', 'expense')", name=op.f("ck_personal_transactions_type")
        ),
        sa.CheckConstraint(
            "amount_minor > 0", name=op.f("ck_personal_transactions_amount_positive")
        ),
        sa.ForeignKeyConstraint(
            ["acting_admin_id"],
            ["users.id"],
            name=op.f("fk_personal_transactions_acting_admin_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_personal_transactions_category_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_personal_transactions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_personal_transactions")),
    )
    op.create_index(
        "ix_personal_transactions_user_date",
        "personal_transactions",
        ["user_id", sa.literal_column("date DESC")],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "settlements",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("from_user", sa.UUID(), nullable=False),
        sa.Column("to_user", sa.UUID(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("acting_admin_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "method IN ('upi', 'cash', 'bank', 'other')", name=op.f("ck_settlements_method")
        ),
        sa.CheckConstraint("amount_minor > 0", name=op.f("ck_settlements_amount_positive")),
        sa.CheckConstraint("from_user <> to_user", name=op.f("ck_settlements_different_people")),
        sa.ForeignKeyConstraint(
            ["acting_admin_id"], ["users.id"], name=op.f("fk_settlements_acting_admin_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_settlements_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["from_user"], ["users.id"], name=op.f("fk_settlements_from_user_users")
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_settlements_group_id_groups")
        ),
        sa.ForeignKeyConstraint(
            ["to_user"], ["users.id"], name=op.f("fk_settlements_to_user_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settlements")),
    )
    op.create_index(
        "ix_settlements_group",
        "settlements",
        ["group_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "expenses",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("payer_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("split_method", sa.Text(), nullable=False),
        sa.Column("import_batch_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("acting_admin_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint("amount_minor > 0", name=op.f("ck_expenses_amount_positive")),
        sa.ForeignKeyConstraint(
            ["acting_admin_id"], ["users.id"], name=op.f("fk_expenses_acting_admin_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("fk_expenses_category_id_categories")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_expenses_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_expenses_group_id_groups")
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_expenses_import_batch_id_import_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["payer_id"], ["users.id"], name=op.f("fk_expenses_payer_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expenses")),
    )
    op.create_index(
        "ix_expenses_group_date",
        "expenses",
        ["group_id", sa.literal_column("date DESC")],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_expenses_import_batch_id"), "expenses", ["import_batch_id"], unique=False
    )
    op.create_table(
        "expense_splits",
        sa.Column("expense_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("share_minor", sa.BigInteger(), nullable=False),
        sa.Column("input_value", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.CheckConstraint("share_minor >= 0", name=op.f("ck_expense_splits_share_not_negative")),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expenses.id"],
            name=op.f("fk_expense_splits_expense_id_expenses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_expense_splits_user_id_users")
        ),
        sa.PrimaryKeyConstraint("expense_id", "user_id", name=op.f("pk_expense_splits")),
    )
    op.create_index(op.f("ix_expense_splits_user_id"), "expense_splits", ["user_id"], unique=False)
    # ### end Alembic commands ###
    op.execute(SPLIT_SUM_CHECK)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER expenses_split_sum_matches ON expenses")
    op.execute("DROP TRIGGER expense_splits_sum_matches ON expense_splits")
    op.execute("DROP FUNCTION check_expense_split_sum()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expense_splits_user_id"), table_name="expense_splits")
    op.drop_table("expense_splits")
    op.drop_index(op.f("ix_expenses_import_batch_id"), table_name="expenses")
    op.drop_index(
        "ix_expenses_group_date",
        table_name="expenses",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("expenses")
    op.drop_index(
        "ix_settlements_group",
        table_name="settlements",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("settlements")
    op.drop_index(
        "ix_personal_transactions_user_date",
        table_name="personal_transactions",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("personal_transactions")
    op.drop_table("import_batches")
    op.drop_index(op.f("ix_group_members_user_id"), table_name="group_members")
    op.drop_table("group_members")
    op.drop_index("ix_activity_events_group_at", table_name="activity_events")
    op.drop_table("activity_events")
    op.drop_table("groups")
    op.drop_index(
        "uq_categories_system_key",
        table_name="categories",
        postgresql_where=sa.text("owner_id IS NULL"),
    )
    op.drop_index(
        "uq_categories_owner_key",
        table_name="categories",
        postgresql_where=sa.text("owner_id IS NOT NULL"),
    )
    op.drop_table("categories")
    op.drop_index("ix_audit_logs_at", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("ix_analytics_configuration_scope_owner", table_name="analytics_configuration")
    op.drop_table("analytics_configuration")
    op.drop_table("admin_sessions")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
