"""sync log and versions

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 20:34:48.439579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_streams',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('head_seq', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('oldest_seq', sa.BigInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_streams'))
    )
    op.create_table('change_log',
    sa.Column('stream_id', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('op', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('acting_admin_id', sa.UUID(), nullable=True),
    sa.Column('schema_version', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("op IN ('upsert', 'delete')", name=op.f('ck_change_log_op')),
    sa.ForeignKeyConstraint(['acting_admin_id'], ['users.id'], name=op.f('fk_change_log_acting_admin_id_users')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_change_log_actor_id_users')),
    sa.ForeignKeyConstraint(['stream_id'], ['sync_streams.id'], name=op.f('fk_change_log_stream_id_sync_streams')),
    sa.PrimaryKeyConstraint('stream_id', 'seq', name=op.f('pk_change_log'))
    )
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity', 'entity_id'], unique=False)
    op.add_column('expenses', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('groups', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('personal_transactions', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('settlements', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'version')
    op.drop_column('settlements', 'version')
    op.drop_column('personal_transactions', 'version')
    op.drop_column('groups', 'version')
    op.drop_column('expenses', 'version')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_table('change_log')
    op.drop_table('sync_streams')
    # ### end Alembic commands ###
